$ErrorActionPreference = 'Stop'

function Assert-True {
    param(
        [Parameter(Mandatory = $true)]
        [bool]$Condition,

        [Parameter(Mandatory = $true)]
        [string]$Message
    )

    if (-not $Condition) {
        throw $Message
    }
}

function Assert-Contains {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$Needle
    )

    $content = Get-Content -LiteralPath $Path -Raw

    if (-not $content.Contains($Needle)) {
        throw "Expected '$Path' to contain '$Needle'."
    }
}

$scriptPath = Join-Path $PSScriptRoot 'New-ProductPipelineRunFromPacket.ps1'
$tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("product-pipeline-run-test-" + [System.Guid]::NewGuid().ToString('N'))
$packetPath = Join-Path $tempRoot 'packet-draft.md'
$runRoot = Join-Path $tempRoot 'runs'
$proposalRoot = Join-Path $tempRoot 'proposals'

New-Item -ItemType Directory -Path $tempRoot | Out-Null

try {
    @'
# Product Pipeline Packet Draft - Launch Intake Desk

This packet draft was generated from an accepted Launch Intake request. It is review material only. Do not create GitHub issues from this draft.

## Packet Metadata

- Packet name: Launch Intake Desk
- Packet id: launch-intake-seed-launch-intake-request
- Packet version: 0.1-draft
- Packet status: Draft Ready for Product Pipeline review
- Parent KB path: `C:/Projects/Nodera-LaunchIntake-Pilot/kb`
- Active parent project: `launch-intake-pilot`
- Source app workspace: `demo-workspace`
- Product Pipeline run path: Not generated by this exporter.
- Source proposal: Not generated by this exporter.
- Source issue: Not created by this exporter.
- Source request: `seed-launch-intake-request`
- Accepted writeback source: `C:/Projects/Nodera-LaunchIntake-Pilot/kb/projects/launch-intake-pilot/product/release-slices/launch-intake-accepted-writeback.md`
- Draft output path: `C:/Projects/Nodera-LaunchIntake-Pilot/kb/projects/launch-intake-pilot/product/packet-drafts/launch-intake-desk-packet-draft.md`
- Generated at: 2026-05-19T04:09:17.529Z
- Created by: Demo User <demo@nexa.local>

## Source Idea

- Raw idea: Launch Intake Desk
- Human guidance: None recorded.
- Target user or buyer: Founders and product operators
- Problem or opportunity: Promising ideas are scattered across chat and do not become durable, reviewable work.
- Desired outcome: A reviewed Product Pipeline packet and app-ready implementation brief.
- First wedge: Review this packet draft and decide whether Product Pipeline should create the full artifact set.
- Why this is reusable: Accepted intake records can use this packet shape before becoming Product Pipeline runs, KB work, or AppBuilder work.
- Non-goals: Do not create GitHub issues from this draft. Do not infer design, billing, hosting, mobile, desktop, or implementation scope.
'@ | Set-Content -LiteralPath $packetPath -Encoding UTF8

    & $scriptPath `
        -PacketDraftPath $packetPath `
        -OutputRoot $runRoot `
        -ProposalRoot $proposalRoot `
        -RunDate '2026-05-19' `
        -GeneratedAt '2026-05-19T12:00:00.000Z'

    $runPath = Join-Path $runRoot '2026-05-19-launch-intake-desk-artifact-run'
    $proposalPath = Join-Path $proposalRoot '2026-05-19-launch-intake-desk-artifact-run-proposal.md'

    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'README.md')) 'Run README was not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'intake-notes.md')) 'Intake notes were not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'research-brief.md')) 'Research brief was not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'comparative-analysis.md')) 'Comparative analysis was not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'opportunity-brief.md')) 'Opportunity brief was not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'epic-map.md')) 'Epic map was not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'design-brief.md')) 'Design brief was not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'issue-candidates.md')) 'Issue candidates were not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'readiness-review.md')) 'Readiness review was not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'parent-kb-update-plan.md')) 'Parent KB update plan was not generated.'
    Assert-True (Test-Path -LiteralPath (Join-Path $runPath 'launch-intake-packet.md')) 'Launch packet copy was not generated.'
    Assert-True (Test-Path -LiteralPath $proposalPath) 'GitHub output proposal was not generated.'

    Assert-Contains (Join-Path $runPath 'README.md') 'Generated From Packet Draft'
    Assert-Contains (Join-Path $runPath 'README.md') 'Source request: `seed-launch-intake-request`'
    Assert-Contains (Join-Path $runPath 'intake-notes.md') 'Promising ideas are scattered across chat'
    Assert-Contains (Join-Path $runPath 'issue-candidates.md') 'Do not create GitHub issues from this generated run without proposal approval.'
    Assert-Contains (Join-Path $runPath 'readiness-review.md') 'not Dev Ready'
    Assert-Contains (Join-Path $runPath 'parent-kb-update-plan.md') 'C:/Projects/Nodera-LaunchIntake-Pilot/kb'
    Assert-Contains $proposalPath 'Review Required'

    $overwriteBlocked = $false

    try {
        & $scriptPath `
            -PacketDraftPath $packetPath `
            -OutputRoot $runRoot `
            -ProposalRoot $proposalRoot `
            -RunDate '2026-05-19' `
            -GeneratedAt '2026-05-19T12:00:00.000Z'
    } catch {
        $overwriteBlocked = $_.Exception.Message.Contains('already exists')
    }

    Assert-True $overwriteBlocked 'Generator did not block overwrite without -Force.'

    $defaultToolRoot = Join-Path $tempRoot 'product-pipeline\tools'
    New-Item -ItemType Directory -Path $defaultToolRoot -Force | Out-Null
    $defaultScriptPath = Join-Path $defaultToolRoot 'New-ProductPipelineRunFromPacket.ps1'
    Copy-Item -LiteralPath $scriptPath -Destination $defaultScriptPath

    & $defaultScriptPath `
        -PacketDraftPath $packetPath `
        -RunDate '2026-05-20' `
        -GeneratedAt '2026-05-20T12:00:00.000Z'

    $defaultRunPath = Join-Path $tempRoot 'product-pipeline\runs\2026-05-20-launch-intake-desk-artifact-run'
    $defaultProposalPath = Join-Path $tempRoot 'product-pipeline\proposals\2026-05-20-launch-intake-desk-artifact-run-proposal.md'

    Assert-True (Test-Path -LiteralPath (Join-Path $defaultRunPath 'README.md')) 'Default run root was not resolved from script location.'
    Assert-True (Test-Path -LiteralPath $defaultProposalPath) 'Default proposal root was not resolved from script location.'

    $escapeRoot = Join-Path $tempRoot 'escape-runs'
    $escapeProposalRoot = Join-Path $tempRoot 'escape-proposals'

    & $scriptPath `
        -PacketDraftPath $packetPath `
        -OutputRoot $escapeRoot `
        -ProposalRoot $escapeProposalRoot `
        -RunDate '2026-05-21' `
        -RunSlug '..\outside path' `
        -GeneratedAt '2026-05-21T12:00:00.000Z'

    Assert-True (Test-Path -LiteralPath (Join-Path $escapeRoot '2026-05-21-outside-path\README.md')) 'Explicit run slug was not sanitized.'
    Assert-True (-not (Test-Path -LiteralPath (Join-Path $tempRoot 'outside path'))) 'Explicit run slug escaped the output root.'

    'Product Pipeline packet-to-run generator tests passed.'
} finally {
    if (Test-Path -LiteralPath $tempRoot) {
        Remove-Item -LiteralPath $tempRoot -Recurse -Force
    }
}
